name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  go-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Verify dependencies (go mod tidy)
        run: |
          go mod tidy && echo "Go is tidy"

      - name: Build package
        run: go build ./...

      - name: Vet package
        run: go vet ./...

      - name: Run tests
        run: go test ./...
